import { useEffect, useState, useContext } from 'react'
import Head from 'next/head'
import Login from "./components/Login"

export default function Home() {
  const [ct, setCt] = useState(120);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="prose">
        <article>
          <h1>Garlic bread with cheese: What the science tells us {ct}</h1>
          <p>For years parents have espoused the health benefits of eating garlic bread with cheese to their children, with the food earning such an iconic status in our culture that kids will often dress up as warm, cheesy loaf for Halloween.</p>
          <p>But a recent study shows that the celebrated appetizer may be linked to a series of rabies cases springing up around the country.</p>
        </article>

        <button className="btn btn-primary" onClick={()=>{setCt(ct+1)}}>test</button>

        <Login />
      </main>


    </div>
  )
}
